# Generated by Django 4.0.2 on 2022-03-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.base')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-created_on'],
            },
            bases=('blog.base',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.base')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_on'],
            },
            bases=('blog.base',),
        ),
    ]
