# Generated by Django 4.0.2 on 2022-03-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subcategory_id',
            new_name='subcategory_name',
        ),
    ]
