# Generated by Django 4.0.2 on 2022-02-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='base_ptr',
        ),
        migrations.AddField(
            model_name='post',
            name='category_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.category'),
            preserve_default=False,
        ),
    ]
