# Generated by Django 4.0.2 on 2022-02-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_base_ptr_post_category_ptr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
    ]
