# Generated by Django 4.0.2 on 2022-02-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.category')),
                ('suncategory_name', models.CharField(max_length=10)),
            ],
            bases=('blog.category',),
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_ptr',
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.subcategory'),
            preserve_default=False,
        ),
    ]
