# Generated by Django 4.0.2 on 2022-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subcategory_remove_post_category_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='suncategory_name',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_no',
            field=models.IntegerField(choices=[(0, 'Language'), (1, 'Travel'), (1, 'Health')], default=0),
        ),
    ]
